# Generated by Django 4.2.4 on 2023-08-21 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step1', models.TextField(blank=True, null=True)),
                ('step2', models.TextField(blank=True, null=True)),
                ('step3', models.TextField(blank=True, null=True)),
                ('step4', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'Forms',
            },
        ),
    ]
