# Generated by Django 4.2.4 on 2023-08-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
