# Generated by Django 4.2.4 on 2023-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_forms_email_forms_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Erkek'), (1, 'Kadın')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forms',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
